//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public string ID { get; set; }
        public Nullable<int> NumPercent { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
